package keygen

import (
	"errors"
	"fmt"

	"github.com/xlabs/multi-party-sig/internal/types"
	"github.com/xlabs/multi-party-sig/pkg/math/curve"
	"github.com/xlabs/multi-party-sig/pkg/math/polynomial"
	"github.com/xlabs/multi-party-sig/pkg/party"
	"github.com/xlabs/multi-party-sig/pkg/round"
	zkfac "github.com/xlabs/multi-party-sig/pkg/zk/fac"
	zkmod "github.com/xlabs/multi-party-sig/pkg/zk/mod"
	zkprm "github.com/xlabs/multi-party-sig/pkg/zk/prm"
	"github.com/xlabs/multi-party-sig/protocols/cmp/config"
	common "github.com/xlabs/tss-common"
)

var _ round.Round = (*round4)(nil)

type round4 struct {
	*round3

	// RID = ⊕ⱼ RIDⱼ
	// Random ID generated by taking the XOR of all ridᵢ
	RID types.RID
	// ChainKey is a sequence of random bytes agreed upon together
	ChainKey types.RID

	validMod  map[party.ID]bool
	validPrms map[party.ID]bool
}

// StoreBroadcastMessage implements round.BroadcastRound.
//
// - verify Mod, Prm proof for N
func (r *round4) StoreBroadcastMessage(msg round.Message) error {
	from := msg.From
	body, ok := msg.Content.(*Broadcast4)
	if !ok || !body.ValidateBasic() {
		return round.ErrInvalidContent
	}

	mod, prm, err := body.UnmarshalContent()
	if err != nil {
		return err
	}

	// verify zkmod
	if !mod.Verify(zkmod.Public{N: r.Pedersen[from].N()}, r.HashForID(from), r.Pool) {
		return errors.New("failed to validate mod proof")
	}

	// verify zkprm
	if !prm.Verify(zkprm.Public{Aux: r.Pedersen[from]}, r.HashForID(from), r.Pool) {
		return errors.New("failed to validate prm proof")
	}

	r.validMod[from] = true
	r.validPrms[from] = true

	return nil
}

// VerifyMessage implements round.Round.
//
// - verify validity of share ciphertext.

// TODO: Consider this a nil function, and modify the API of round.Round (verify the message inside StoreMessage).
func (r *round4) VerifyMessage(msg round.Message) error {
	from := msg.From
	body, ok := msg.Content.(*Message4)
	if !ok || !body.ValidateBasic() {
		return round.ErrInvalidContent
	}

	ctx, fac, err := body.UnmarshalContent()
	if err != nil {
		return fmt.Errorf("failed to unmarshal Message4 content: %w", err)
	}

	if !r.PaillierPublic[msg.To].ValidateCiphertexts(ctx) {
		return errors.New("invalid ciphertext")
	}

	// verify zkfac
	if !fac.Verify(zkfac.Public{N: r.PaillierPublic[from].N(), Aux: r.Pedersen[msg.To]}, r.HashForID(from)) {
		return errors.New("failed to validate fac proof")
	}

	return nil
}

// StoreMessage implements round.Round.
//
// Since this message is only intended for us, we need to do the VSS verification here.
// - check that the decrypted share did not overflow.
// - check VSS condition.
// - save share.
func (r *round4) StoreMessage(msg round.Message) error {
	from, body := msg.From, msg.Content.(*Message4)
	// TODO: I think that verify should store after verification the ctxShare and use it here instead of unmarshalling.
	//       Note that round.Message in the original code is *message4, which is in unmarshaled representation.
	share, _, err := body.UnmarshalContent()
	if err != nil {
		return fmt.Errorf("failed to unmarshal Message4 content: %w", err)
	}

	// decrypt share
	DecryptedShare, err := r.PaillierSecret.Dec(share)
	if err != nil {
		return err
	}

	Share := r.Group().NewScalar().SetNat(DecryptedShare.Mod(r.Group().Order()))
	if DecryptedShare.Eq(curve.MakeInt(Share)) != 1 {
		return errors.New("decrypted share is not in correct range")
	}

	// verify share with VSS
	ExpectedPublicShare := r.VSSPolynomials[from].Evaluate(r.SelfID().Scalar(r.Group())) // Fⱼ(i)
	PublicShare := Share.ActOnBase()
	// X == Fⱼ(i)
	if !PublicShare.Equal(ExpectedPublicShare) {
		return errors.New("failed to validate VSS share")
	}

	r.ShareReceived[from] = Share
	return nil
}

// Finalize implements round.Round
//
// - sum of all received shares
// - compute group public key and individual public keys
// - recompute config SSID
// - validate Config
// - write new ssid hash to old hash state
// - create proof of knowledge of secret.
func (r *round4) Finalize(out chan<- common.ParsedMessage) (round.Session, error) {
	// add all shares to our secret
	UpdatedSecretECDSA := r.Group().NewScalar()
	if r.PreviousSecretECDSA != nil {
		UpdatedSecretECDSA.Set(r.PreviousSecretECDSA)
	}
	for _, j := range r.PartyIDs() {
		UpdatedSecretECDSA.Add(r.ShareReceived[j])
	}

	// [F₁(X), …, Fₙ(X)]
	ShamirPublicPolynomials := make([]*polynomial.Exponent, 0, len(r.VSSPolynomials))
	for _, VSSPolynomial := range r.VSSPolynomials {
		ShamirPublicPolynomials = append(ShamirPublicPolynomials, VSSPolynomial)
	}

	// ShamirPublicPolynomial = F(X) = ∑Fⱼ(X)
	ShamirPublicPolynomial, err := polynomial.Sum(ShamirPublicPolynomials)
	if err != nil {
		return r, err
	}

	// compute the new public key share Xⱼ = F(j) (+X'ⱼ if doing a refresh)
	PublicData := make(map[party.ID]*config.Public, len(r.PartyIDs()))
	for _, j := range r.PartyIDs() {
		PublicECDSAShare := ShamirPublicPolynomial.Evaluate(j.Scalar(r.Group()))
		if r.PreviousPublicSharesECDSA != nil {
			PublicECDSAShare = PublicECDSAShare.Add(r.PreviousPublicSharesECDSA[j])
		}
		PublicData[j] = &config.Public{
			ECDSA:    PublicECDSAShare,
			ElGamal:  r.ElGamalPublic[j],
			Paillier: r.PaillierPublic[j],
			Pedersen: r.Pedersen[j],
		}
	}

	UpdatedConfig := &config.Config{
		Group:     r.Group(),
		ID:        r.SelfID(),
		Threshold: r.Threshold(),
		ECDSA:     UpdatedSecretECDSA,
		ElGamal:   r.ElGamalSecret,
		Paillier:  r.PaillierSecret,
		RID:       r.RID.Copy(),
		ChainKey:  r.ChainKey.Copy(),
		Public:    PublicData,
	}

	// write new ssid to hash, to bind the Schnorr proof to this new config
	// Write SSID, selfID to temporary hash
	h := r.Hash()
	_ = h.WriteAny(UpdatedConfig, r.SelfID())

	proof := r.SchnorrRand.Prove(h, PublicData[r.SelfID()].ECDSA, UpdatedSecretECDSA, nil)

	broadcast5, err := makeBroadcast5(proof)
	if err != nil {
		return r, err
	}

	// send to all
	err = r.BroadcastMessage(out, broadcast5)
	if err != nil {
		return r, err
	}

	r.UpdateHashState(UpdatedConfig)
	return &round5{
		round4:           r,
		UpdatedConfig:    UpdatedConfig,
		validSchnorrResp: map[party.ID]bool{r.SelfID(): true},
	}, nil
}

// MessageContent implements round.Round.
func (round4) MessageContent() round.Content { return &Message4{} }

// BroadcastContent implements round.BroadcastRound.
func (round4) BroadcastContent() round.BroadcastContent {
	return &Broadcast4{
		Mod: []byte{},
		Prm: []byte{},
	}
}

// Number implements round.Round.
func (round4) Number() round.Number { return 4 }

func (r *round4) CanFinalize() bool {
	t := r.Threshold() + 1

	if len(r.validPrms) < t || len(r.validMod) < t || len(r.ShareReceived) < t {
		return false
	}

	// should ensure each party sent validMod and validPrms
	for _, p := range r.PartyIDs() {
		if !r.validMod[p] || !r.validPrms[p] {
			return false
		}

		if _, ok := r.ShareReceived[p]; !ok {
			return false
		}
	}

	return true
}
