// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/cmp-signing.proto

package sign

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Broadcast2 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// K = Kᵢ
	K []byte `protobuf:"bytes,1,opt,name=K,proto3" json:"K,omitempty"`
	// G = Gᵢ
	G             []byte `protobuf:"bytes,2,opt,name=G,proto3" json:"G,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broadcast2) Reset() {
	*x = Broadcast2{}
	mi := &file_proto_cmp_signing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broadcast2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast2) ProtoMessage() {}

func (x *Broadcast2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmp_signing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast2.ProtoReflect.Descriptor instead.
func (*Broadcast2) Descriptor() ([]byte, []int) {
	return file_proto_cmp_signing_proto_rawDescGZIP(), []int{0}
}

func (x *Broadcast2) GetK() []byte {
	if x != nil {
		return x.K
	}
	return nil
}

func (x *Broadcast2) GetG() []byte {
	if x != nil {
		return x.G
	}
	return nil
}

type Message2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProofEnc      []byte                 `protobuf:"bytes,1,opt,name=ProofEnc,proto3" json:"ProofEnc,omitempty"` // *zkenc.Proof
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message2) Reset() {
	*x = Message2{}
	mi := &file_proto_cmp_signing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message2) ProtoMessage() {}

func (x *Message2) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmp_signing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message2.ProtoReflect.Descriptor instead.
func (*Message2) Descriptor() ([]byte, []int) {
	return file_proto_cmp_signing_proto_rawDescGZIP(), []int{1}
}

func (x *Message2) GetProofEnc() []byte {
	if x != nil {
		return x.ProofEnc
	}
	return nil
}

type Broadcast3 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BigGammaShare = Γⱼ; a curve.Point
	BigGammaShare []byte `protobuf:"bytes,1,opt,name=BigGammaShare,proto3" json:"BigGammaShare,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Broadcast3) Reset() {
	*x = Broadcast3{}
	mi := &file_proto_cmp_signing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Broadcast3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast3) ProtoMessage() {}

func (x *Broadcast3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmp_signing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast3.ProtoReflect.Descriptor instead.
func (*Broadcast3) Descriptor() ([]byte, []int) {
	return file_proto_cmp_signing_proto_rawDescGZIP(), []int{2}
}

func (x *Broadcast3) GetBigGammaShare() []byte {
	if x != nil {
		return x.BigGammaShare
	}
	return nil
}

type Message3 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// DeltaBeta   *paillier.Ciphertext // DeltaBeta = βᵢⱼ
	DeltaBeta []byte `protobuf:"bytes,1,opt,name=DeltaBeta,proto3" json:"DeltaBeta,omitempty"`
	// ChiBeta     *paillier.Ciphertext // ChiBeta = β̂ᵢⱼ
	ChiBeta []byte `protobuf:"bytes,2,opt,name=ChiBeta,proto3" json:"ChiBeta,omitempty"`
	// DeltaD      *paillier.Ciphertext // DeltaD = Dᵢⱼ
	DeltaD []byte `protobuf:"bytes,3,opt,name=DeltaD,proto3" json:"DeltaD,omitempty"`
	// DeltaF     *paillier.Ciphertext // DeltaF = Fᵢⱼ
	DeltaF []byte `protobuf:"bytes,4,opt,name=DeltaF,proto3" json:"DeltaF,omitempty"`
	// DeltaProof *zkaffg.Proof
	DeltaProof []byte `protobuf:"bytes,5,opt,name=DeltaProof,proto3" json:"DeltaProof,omitempty"`
	// ChiD       *paillier.Ciphertext // DeltaD = D̂_{ij}
	ChiD []byte `protobuf:"bytes,6,opt,name=ChiD,proto3" json:"ChiD,omitempty"`
	// ChiF       *paillier.Ciphertext // ChiF = F̂ᵢⱼ
	ChiF []byte `protobuf:"bytes,7,opt,name=ChiF,proto3" json:"ChiF,omitempty"`
	// ChiProof   *zkaffg.Proof
	ChiProof []byte `protobuf:"bytes,8,opt,name=ChiProof,proto3" json:"ChiProof,omitempty"`
	// ProofLog   *zklogstar.Proof
	ProofLog      []byte `protobuf:"bytes,9,opt,name=ProofLog,proto3" json:"ProofLog,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message3) Reset() {
	*x = Message3{}
	mi := &file_proto_cmp_signing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message3) ProtoMessage() {}

func (x *Message3) ProtoReflect() protoreflect.Message {
	mi := &file_proto_cmp_signing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message3.ProtoReflect.Descriptor instead.
func (*Message3) Descriptor() ([]byte, []int) {
	return file_proto_cmp_signing_proto_rawDescGZIP(), []int{3}
}

func (x *Message3) GetDeltaBeta() []byte {
	if x != nil {
		return x.DeltaBeta
	}
	return nil
}

func (x *Message3) GetChiBeta() []byte {
	if x != nil {
		return x.ChiBeta
	}
	return nil
}

func (x *Message3) GetDeltaD() []byte {
	if x != nil {
		return x.DeltaD
	}
	return nil
}

func (x *Message3) GetDeltaF() []byte {
	if x != nil {
		return x.DeltaF
	}
	return nil
}

func (x *Message3) GetDeltaProof() []byte {
	if x != nil {
		return x.DeltaProof
	}
	return nil
}

func (x *Message3) GetChiD() []byte {
	if x != nil {
		return x.ChiD
	}
	return nil
}

func (x *Message3) GetChiF() []byte {
	if x != nil {
		return x.ChiF
	}
	return nil
}

func (x *Message3) GetChiProof() []byte {
	if x != nil {
		return x.ChiProof
	}
	return nil
}

func (x *Message3) GetProofLog() []byte {
	if x != nil {
		return x.ProofLog
	}
	return nil
}

var File_proto_cmp_signing_proto protoreflect.FileDescriptor

const file_proto_cmp_signing_proto_rawDesc = "" +
	"\n" +
	"\x17proto/cmp-signing.proto\x12\x0exlabs.cmp.sign\"(\n" +
	"\n" +
	"Broadcast2\x12\f\n" +
	"\x01K\x18\x01 \x01(\fR\x01K\x12\f\n" +
	"\x01G\x18\x02 \x01(\fR\x01G\"&\n" +
	"\bMessage2\x12\x1a\n" +
	"\bProofEnc\x18\x01 \x01(\fR\bProofEnc\"2\n" +
	"\n" +
	"Broadcast3\x12$\n" +
	"\rBigGammaShare\x18\x01 \x01(\fR\rBigGammaShare\"\xf2\x01\n" +
	"\bMessage3\x12\x1c\n" +
	"\tDeltaBeta\x18\x01 \x01(\fR\tDeltaBeta\x12\x18\n" +
	"\aChiBeta\x18\x02 \x01(\fR\aChiBeta\x12\x16\n" +
	"\x06DeltaD\x18\x03 \x01(\fR\x06DeltaD\x12\x16\n" +
	"\x06DeltaF\x18\x04 \x01(\fR\x06DeltaF\x12\x1e\n" +
	"\n" +
	"DeltaProof\x18\x05 \x01(\fR\n" +
	"DeltaProof\x12\x12\n" +
	"\x04ChiD\x18\x06 \x01(\fR\x04ChiD\x12\x12\n" +
	"\x04ChiF\x18\a \x01(\fR\x04ChiF\x12\x1a\n" +
	"\bChiProof\x18\b \x01(\fR\bChiProof\x12\x1a\n" +
	"\bProofLog\x18\t \x01(\fR\bProofLogB\x14Z\x12protocols/cmp/signb\x06proto3"

var (
	file_proto_cmp_signing_proto_rawDescOnce sync.Once
	file_proto_cmp_signing_proto_rawDescData []byte
)

func file_proto_cmp_signing_proto_rawDescGZIP() []byte {
	file_proto_cmp_signing_proto_rawDescOnce.Do(func() {
		file_proto_cmp_signing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_cmp_signing_proto_rawDesc), len(file_proto_cmp_signing_proto_rawDesc)))
	})
	return file_proto_cmp_signing_proto_rawDescData
}

var file_proto_cmp_signing_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_cmp_signing_proto_goTypes = []any{
	(*Broadcast2)(nil), // 0: xlabs.cmp.sign.Broadcast2
	(*Message2)(nil),   // 1: xlabs.cmp.sign.Message2
	(*Broadcast3)(nil), // 2: xlabs.cmp.sign.Broadcast3
	(*Message3)(nil),   // 3: xlabs.cmp.sign.Message3
}
var file_proto_cmp_signing_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cmp_signing_proto_init() }
func file_proto_cmp_signing_proto_init() {
	if File_proto_cmp_signing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_cmp_signing_proto_rawDesc), len(file_proto_cmp_signing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_cmp_signing_proto_goTypes,
		DependencyIndexes: file_proto_cmp_signing_proto_depIdxs,
		MessageInfos:      file_proto_cmp_signing_proto_msgTypes,
	}.Build()
	File_proto_cmp_signing_proto = out.File
	file_proto_cmp_signing_proto_goTypes = nil
	file_proto_cmp_signing_proto_depIdxs = nil
}
